### ISSUE TITLE
Add support for archiving and uploading the created bazel modules

### ISSUE THREAD

**Issue by shabanzd** [shabanzd/dependency-bazelizer#14]
**Background**

Currently, the created modules are saved in the repo as local_path modules. It is useful to also support archiving the modules and uploading them to some storage.

The registry entries will also have to be different in that case (especially the source.json file). 

**Action Points**
* Find a generic way to support uploading modules as archives.
* Adapt the logic of writing registry entries (source.json of each module).

**Acceptance Criteria**
* The use-case of uploading modules as archives is supported.

**Comment by mattvonarx** [comment]
Perhaps it would be best to have the modules use http_archive to download and extract the debian packages, so the binaries do not have to even be a part of the equation.

**Comment by shabanzd** [comment]
Do you mean implementing a module extension and install the .deb archives there ?
