### ISSUE TITLE
Add CI to the repo

### ISSUE THREAD

**Issue by shabanzd** [shabanzd/dependency-bazelizer#6]

**Comment by reu-dev** [comment]
please describe what you want to be tested (command line, platforms), then
I'll take care of it

Am Sa., 6. Mai 2023 um 22:38 Uhr schrieb shabanzd ***@***.***

**Comment by shabanzd** [comment]
Let me add a small test and think what platform to start with and come back ! Thanks Stefan 🤩

**Comment by shabanzd** [comment]
ok we can start with a simple:
`bazelisk build //...`
`bazelisk test //...`
on Ubuntu 20.04
